Pytorch Fundamentals: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
##Tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
##Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
##Matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
##Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6453, 0.0638, 0.1323, 0.0765],
        [0.4056, 0.7047, 0.8535, 0.2178],
        [0.1187, 0.1337, 0.0656, 0.8551]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channels (R,G,B)-first one
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
### Zeros and ones
# tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
ones.dtype

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


torch.float32

In [ ]:
#Create a range of tensors and tensors-like
x = torch.arange(0,10)
y = torch.arange(1,11)
print(x)
print(y)
withsteps = torch.arange(start=0, end=1000, step=77)
print(withsteps)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [ ]:
#tensor-like
ten_zeros = torch.zeros_like(input=x)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
Note: Tensor datatypes is one of the 3 big errors dealing with Pytorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)

Tensors:
https://pytorch.org/docs/stable/tensors.html

In [ ]:
#Tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor(32,16 etc. means how many detailes stored in memory)
                               device=None, #"cpu" or "cuda", what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#convertation, tackle an issue No.1
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

**Getting info from tensors** tensors attributes

datatype - tensor.dtype

shape - tensor.shape

device - tensor.device

In [ ]:
#Example
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device for tensor: {some_tensor.device}")

tensor([[0.4638, 0.5716, 0.6064, 0.3060],
        [0.2293, 0.5045, 0.5668, 0.3137],
        [0.0988, 0.0675, 0.2731, 0.5523]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device for tensor: cpu


#Manipulating tensors (operations)

1.Addition

2.Multiplication (element-wise)

3.Division

4.Subtraction

5.Matrix multiplication

In [ ]:
#Example
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor/10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


**Matrix multiplication**

2 rules:

inner dimensons must match

(3,2 * 2,3)

resalting matrix has the shape of the outer dimensions

(**3**,2 * 2,**3**) === (3,3)


matrixmultiplication.xyz



In [ ]:
#element-wise
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#matrix
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#another way
%%time
##know time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.91 ms, sys: 0 ns, total: 1.91 ms
Wall time: 7.37 ms


In [ ]:
#to fix shape issue-matrix transposition
tensor_A = torch.rand(3,2)
tensor_B = torch.rand(3,2)
tensor_B = tensor_B.T
torch.matmul(tensor_A, tensor_B)

tensor([[0.0675, 0.8722, 1.0748],
        [0.1119, 1.0263, 1.3899],
        [0.0479, 0.3073, 0.4718]])

##Tensor aggregation: min,max,mean,sum,etc.

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x) #or
x.min()

tensor(0)

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x, dtype = torch.float32) #due to error, mean function requires a tensor of float32

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Positional mean and max of tensors

In [ ]:
print(x.argmin()) #index value
x.argmax()

tensor(0)


tensor(9)

## Reshaping, stacking, squeeezing/unsqueezing tensors



*   Reshaping - reshapes an input tensor to a defined shape
*   View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
*   Stacking - combine multiple tensors on top of each other (vstrack) or  side by side (hstack)
*   Squeeze - removes all 1 dimensions from a tensor
*   Unsqueeze - add a 1 dimension to a target tensor
*   Permute - return a view of the input with dimensions permuted (swapped) in a certain way






In [ ]:
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(5 , 2) #should be as initial size
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x_reshaped = x.reshape(2 , 5) #should be compatible with initial size
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# change the view
z = x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
# remove extra dimensons from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 5.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([2, 5])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 5.,  7.,  8.,  9., 10.]])
New shape: torch.Size([2, 5])


In [ ]:
# unsqueeze
x.unsqueezed = x_squeezed.unsqueeze(dim=1)
x.unsqueezed

tensor([[[ 5.,  2.,  3.,  4.,  5.]],

        [[ 5.,  7.,  8.,  9., 10.]]])

In [ ]:
# permute - use with images
x_original = torch.rand(size=(224, 224, 3)) #height, width, color_channels

# permute the original tensor to rearrange the axis (or dim) order (change color_channels and height)
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #color_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Selecting data from tensors

In [ ]:
# Indexing (selecting data from tensors)
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0] #dim =1

In [ ]:
#last dimension
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
x[0][2][2]

tensor(9)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

##Pytorch and Numpy

Data in numpy, want in pytorch tensor --> torch.from_numpy(ndarray)

Pytorch tensor --> Numpy --> torch.Tensor.numpy()

In [ ]:
# numpy srray to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## **Warning:** when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
(torch.from_numpy().type(torch.float32))

In [ ]:
# change the value of array
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness is neural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

https://pytorch.org/docs/stable/notes/randomness.html

https://en.wikipedia.org/wiki/Random_seed

In [ ]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9619, 0.7118, 0.7156, 0.5748],
        [0.4574, 0.0725, 0.7542, 0.3331],
        [0.8394, 0.4680, 0.4265, 0.3893]])
tensor([[0.1591, 0.2680, 0.9547, 0.1106],
        [0.2819, 0.6933, 0.9442, 0.4955],
        [0.3444, 0.6503, 0.3819, 0.5474]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) #for each block of code
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#set up
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
torch.cuda.device_count()

cuda


1

In [ ]:
#putting tensors on GPU
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
#tensor([1, 2, 3]) cpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu
#tensor([1, 2, 3], device='cuda:0')

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# back to CPU (due to numpy, which works only on cpu)
tensor_back = tensor_on_gpu.cpu().numpy()
tensor_back

array([1, 2, 3])